# module: duplicati
# description: Duplicati - Backup solution
# category: Utilities
# depends: (none)
# config_requires:
# port: 8200

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - '${IP_ADDRESS}:8200:8200'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - './duplicati:/config'
      - './duplicati/backups:/backups'
      - '${PWD}:/source'
      - '/etc/localtime:/etc/localtime:ro'
