# module: filebrowser
# description: FileBrowser - Web file manager
# category: Utilities
# depends: (none)
# config_requires:
# port: 8008
# homer_group: manage
# homer_name: FileBrowser
# homer_icon: assets/icons/filebrowser.png
# homer_url: http://locip:8008

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    network_mode: "bridge"
    user: "${PUID}:${PGID}"
    ports:
      - '${IP_ADDRESS}:8008:8080'
    environment:
      - FB_BASEURL=/filebrowser
    volumes:
      - './filebrowser:/config'
      - '${PWD}:/data/mediabox'
