# module: lidarr
# description: Lidarr - Music management
# category: Content Automation
# depends: (none)
# config_requires:
# port: 8686

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - '${IP_ADDRESS}:8686:8686'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - './lidarr:/config'
      - '${DLDIR}/completed:/data/completed'
      - '${MUSICDIR}:/music'
      - '/etc/localtime:/etc/localtime:ro'
