# module: metube
# description: MeTube - YouTube downloader
# category: Download Clients
# depends: (none)
# config_requires:
# port: 8281
# homer_group: get
# homer_name: MeTube
# homer_icon: assets/icons/youtubedl.png
# homer_url: http://locip:8281

services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    network_mode: "bridge"
    ports:
      - '${IP_ADDRESS}:8281:8081'
    volumes:
      - '${MISCDIR}:/downloads'
      - './metube:/state'
      - '/etc/localtime:/etc/localtime:ro'
