# module: minio
# description: MinIO - Object storage
# category: Utilities
# depends: (none)
# config_requires:
# port: 9001
# homer_group: manage
# homer_name: MinIO
# homer_icon: assets/icons/minio.png
# homer_url: http://locip:9001

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-10-24T18-35-07Z
    container_name: minio
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - '${IP_ADDRESS}:9000:9000'
      - '${IP_ADDRESS}:9001:9001'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - './minio:/root/.minio'
      - '${PWD}:/export'
    command: server --console-address ":9001" /export
