# module: netdata
# description: Netdata - System monitoring
# category: System & Monitoring
# depends: (none)
# config_requires:
# port: 19999
# homer_group: monitor
# homer_name: Netdata
# homer_icon: assets/icons/netdata.png
# homer_url: http://locip:19999

services:
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    hostname: '${HOSTNAME}'
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - '${IP_ADDRESS}:19999:19999'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      - PGID=${DOCKERGRP}
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
