# module: nzbget
# description: NZBGet - Usenet downloader
# category: Download Clients
# depends: (none)
# config_requires:
# port: 6789
# homer_group: get
# homer_name: NZBGet
# homer_icon: assets/icons/nzbget.png
# homer_url: http://locip:6789

services:
  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    network_mode: "bridge"
    ports:
      - '${IP_ADDRESS}:6789:6789'
    volumes:
      - './nzbget:/config'
      - '${DLDIR}:/downloads'
