# module: prowlarr
# description: Prowlarr - Indexer manager
# category: Indexers
# depends: (none)
# config_requires:
# port: 9696

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - '${IP_ADDRESS}:9696:9696'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - './prowlarr:/config'
