# module: requestrr
# description: Requestrr - Discord request bot
# category: Request Management
# depends: (none)
# config_requires:
# port: 4545

services:
  requestrr:
    image: lscr.io/linuxserver/requestrr
    container_name: requestrr
    restart: unless-stopped
    network_mode: "bridge"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - '${IP_ADDRESS}:4545:4545'
    volumes:
      - './requestrr:/config'
