# module: sonarr
# description: Sonarr - TV show management
# category: Content Automation
# depends: (none)
# config_requires:
# port: 8989

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - '${IP_ADDRESS}:8989:8989'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - './sonarr:/config'
      - '${DLDIR}/completed:/data/completed'
      - '${TVDIR}:/tv'
      - '/etc/localtime:/etc/localtime:ro'
