# module: tubesync
# description: TubeSync - YouTube channel archiver
# category: Download Clients
# depends: (none)
# config_requires:
# port: 4848
# homer_group: get
# homer_name: TubeSync
# homer_icon: assets/icons/tubesync.png
# homer_url: http://locip:4848

services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - '${IP_ADDRESS}:4848:4848'
    volumes:
      - './tubesync:/config'
      - '${MISCDIR}:/downloads'
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
